// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyOrganizer.Infrastructure.Persistence;

#nullable disable

namespace StudyOrganizer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826164845_AddExternalCourseCleanup")]
    partial class AddExternalCourseCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCourseId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_snapshots_current_course")
                        .HasFilter("\"is_current\"");

                    b.HasIndex("ScanRunId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_snapshots_scan_run_id");

                    b.HasIndex("ScanRunId", "ExternalCourseId");

                    b.ToTable("course_snapshots", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSnapshotItem", b =>
                {
                    b.Property<Guid>("CourseSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_snapshot_id");

                    b.Property<Guid>("ExternalLearningContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_learning_content_id");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalContentKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_content_key");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<string>("MediaType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("CourseSnapshotId", "ExternalLearningContentId");

                    b.HasIndex("CourseSnapshotId", "ExternalContentKey")
                        .IsUnique()
                        .HasDatabaseName("ux_course_snapshot_items_snapshot_key");

                    b.HasIndex("CourseSnapshotId", "ExternalCourseId");

                    b.HasIndex("ExternalLearningContentId", "ExternalCourseId");

                    b.ToTable("course_snapshot_items", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("StudyModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_module_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCourseId");

                    b.HasIndex("StudyModuleId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_subscriptions_study_module_id");

                    b.HasIndex("OwnerId", "ExternalCourseId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_subscriptions_owner_course");

                    b.ToTable("course_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_subscriptions_state", "\"state\" IN ('Pending', 'Active', 'Ended')");
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InactiveSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_since");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("external_courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_external_courses_state", "\"state\" IN ('Inactive', 'Active')");
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ExternalLearningContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalContentKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_content_key");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<string>("MediaType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<DateTimeOffset?>("MetadataPurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_purged_at");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCourseId", "ExternalContentKey")
                        .IsUnique()
                        .HasDatabaseName("ux_external_learning_contents_course_key");

                    b.ToTable("external_learning_contents", null, t =>
                        {
                            t.HasCheckConstraint("ck_external_learning_contents_availability", "\"availability\" IN ('Available', 'Unavailable')");

                            t.HasCheckConstraint("ck_external_learning_contents_type", "\"type\" IN ('File', 'Link', 'Activity')");
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivationSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("activation_subscription_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCourseId")
                        .IsUnique()
                        .HasDatabaseName("ux_scan_runs_running_course")
                        .HasFilter("\"status\" = 'Running'");

                    b.HasIndex("ActivationSubscriptionId", "ExternalCourseId");

                    b.ToTable("scan_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_runs_counts_non_negative", "\"new_count\" >= 0 AND \"updated_count\" >= 0 AND \"unchanged_count\" >= 0 AND \"unavailable_count\" >= 0");

                            t.HasCheckConstraint("ck_scan_runs_status", "\"status\" IN ('Running', 'Succeeded', 'Failed', 'Cancelled', 'Expired')");
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.SourceUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid?>("DetectedByScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("detected_by_scan_run_id");

                    b.Property<Guid>("SubscriptionContentStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_content_state_id");

                    b.HasKey("Id");

                    b.HasIndex("DetectedByScanRunId");

                    b.HasIndex("SubscriptionContentStateId")
                        .IsUnique()
                        .HasDatabaseName("ux_source_updates_subscription_content_state");

                    b.ToTable("source_updates", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.SubscriptionContentState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_subscription_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExternalCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_course_id");

                    b.Property<Guid>("ExternalLearningContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_learning_content_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StudyTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_task_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudyTaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_content_states_study_task")
                        .HasFilter("\"study_task_id\" IS NOT NULL");

                    b.HasIndex("CourseSubscriptionId", "ExternalCourseId");

                    b.HasIndex("CourseSubscriptionId", "ExternalLearningContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_content_states_subscription_content");

                    b.HasIndex("ExternalLearningContentId", "ExternalCourseId");

                    b.ToTable("subscription_content_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscription_content_states_status", "\"status\" IN ('Imported', 'Dismissed')");

                            t.HasCheckConstraint("ck_subscription_content_states_task", "(\"status\" = 'Imported' AND \"study_task_id\" IS NOT NULL) OR (\"status\" = 'Dismissed' AND \"study_task_id\" IS NULL)");
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Domain.Modules.StudyModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_modules_owner_id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Domain.Tasks.StudyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_tasks_module_id");

                    b.HasIndex("ModuleId", "Status")
                        .HasDatabaseName("ix_tasks_module_id_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("StudyOrganizer.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSnapshot", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", null)
                        .WithMany()
                        .HasForeignKey("ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanRunId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSnapshotItem", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.CourseSnapshot", null)
                        .WithMany()
                        .HasForeignKey("CourseSnapshotId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalLearningContent", null)
                        .WithMany()
                        .HasForeignKey("ExternalLearningContentId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ContentSignature", "Signature", b1 =>
                        {
                            b1.Property<Guid>("CourseSnapshotItemCourseSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CourseSnapshotItemExternalLearningContentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("signature_hash")
                                .IsFixedLength();

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("signature_version");

                            b1.HasKey("CourseSnapshotItemCourseSnapshotId", "CourseSnapshotItemExternalLearningContentId");

                            b1.ToTable("course_snapshot_items");

                            b1.WithOwner()
                                .HasForeignKey("CourseSnapshotItemCourseSnapshotId", "CourseSnapshotItemExternalLearningContentId");
                        });

                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.CourseSubscription", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", null)
                        .WithMany()
                        .HasForeignKey("ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Domain.Modules.StudyModule", null)
                        .WithMany()
                        .HasForeignKey("StudyModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", b =>
                {
                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ExternalCourseIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("ExternalCourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalCourseKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("external_course_key");

                            b1.Property<string>("SourceInstance")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("source_instance");

                            b1.Property<string>("SourceType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_type");

                            b1.HasKey("ExternalCourseId");

                            b1.HasIndex("SourceType", "SourceInstance", "ExternalCourseKey")
                                .IsUnique()
                                .HasDatabaseName("ux_external_courses_identity");

                            b1.ToTable("external_courses");

                            b1.WithOwner()
                                .HasForeignKey("ExternalCourseId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ExternalLearningContent", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", null)
                        .WithMany()
                        .HasForeignKey("ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ContentSignature", "Signature", b1 =>
                        {
                            b1.Property<Guid>("ExternalLearningContentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("signature_hash")
                                .IsFixedLength();

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("signature_version");

                            b1.HasKey("ExternalLearningContentId");

                            b1.ToTable("external_learning_contents");

                            b1.WithOwner()
                                .HasForeignKey("ExternalLearningContentId");
                        });

                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.ScanRun", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalCourse", null)
                        .WithMany()
                        .HasForeignKey("ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.CourseSubscription", null)
                        .WithMany()
                        .HasForeignKey("ActivationSubscriptionId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ScanRunCounts", "Counts", b1 =>
                        {
                            b1.Property<Guid>("ScanRunId")
                                .HasColumnType("uuid");

                            b1.Property<int>("New")
                                .HasColumnType("integer")
                                .HasColumnName("new_count");

                            b1.Property<int>("Unavailable")
                                .HasColumnType("integer")
                                .HasColumnName("unavailable_count");

                            b1.Property<int>("Unchanged")
                                .HasColumnType("integer")
                                .HasColumnName("unchanged_count");

                            b1.Property<int>("Updated")
                                .HasColumnType("integer")
                                .HasColumnName("updated_count");

                            b1.HasKey("ScanRunId");

                            b1.ToTable("scan_runs");

                            b1.WithOwner()
                                .HasForeignKey("ScanRunId");
                        });

                    b.Navigation("Counts")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.SourceUpdate", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("DetectedByScanRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.SubscriptionContentState", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionContentStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ContentSignature", "DetectedSignature", b1 =>
                        {
                            b1.Property<Guid>("SourceUpdateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("detected_signature_hash")
                                .IsFixedLength();

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("detected_signature_version");

                            b1.HasKey("SourceUpdateId");

                            b1.ToTable("source_updates");

                            b1.WithOwner()
                                .HasForeignKey("SourceUpdateId");
                        });

                    b.Navigation("DetectedSignature")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.ExternalCourses.SubscriptionContentState", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.Tasks.StudyTask", null)
                        .WithMany()
                        .HasForeignKey("StudyTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.CourseSubscription", null)
                        .WithMany()
                        .HasForeignKey("CourseSubscriptionId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyOrganizer.Domain.ExternalCourses.ExternalLearningContent", null)
                        .WithMany()
                        .HasForeignKey("ExternalLearningContentId", "ExternalCourseId")
                        .HasPrincipalKey("Id", "ExternalCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("StudyOrganizer.Domain.ExternalCourses.ContentSignature", "ConfirmedSignature", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionContentStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("confirmed_signature_hash")
                                .IsFixedLength();

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("confirmed_signature_version");

                            b1.HasKey("SubscriptionContentStateId");

                            b1.ToTable("subscription_content_states");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionContentStateId");
                        });

                    b.Navigation("ConfirmedSignature")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.Modules.StudyModule", b =>
                {
                    b.HasOne("StudyOrganizer.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyOrganizer.Domain.Tasks.StudyTask", b =>
                {
                    b.HasOne("StudyOrganizer.Domain.Modules.StudyModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
